services:
  backend:
    build:
      context: ../lab3-back
    container_name: lab3-backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:17
    container_name: lab3-db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ../lab3-back/db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lab3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lab3"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab3-frontend
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:

